---
# Main playbook for setting up development environment
- name: Setup Development Environment
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - vars/packages.yml
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install common development packages
      apt:
        name: "{{ common_packages }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install programming language tools
      apt:
        name: "{{ programming_tools }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install version control tools
      apt:
        name: "{{ version_control_tools }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install database tools
      apt:
        name: "{{ database_tools }}"
        state: present
      when: 
        - ansible_os_family == "Debian"
        - install_databases | default(true)

    - name: Install containerization tools
      apt:
        name: "{{ container_tools }}"
        state: present
      when: 
        - ansible_os_family == "Debian"
        - install_containers | default(true)

    - name: Install text editors and IDEs
      apt:
        name: "{{ editor_tools }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Node.js using NodeSource repository
      block:
        - name: Add NodeSource GPG key
          apt_key:
            url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
            state: present
          when: install_nodejs | default(false)

        - name: Add NodeSource repository
          apt_repository:
            repo: "deb https://deb.nodesource.com/node_{{ nodejs_version | default('18') }}.x {{ ansible_distribution_release }} main"
            state: present
          when: install_nodejs | default(false)

        - name: Install Node.js
          apt:
            name: nodejs
            state: present
          when: install_nodejs | default(false)
      when: ansible_os_family == "Debian"

    - name: Create workspace directory
      file:
        path: /home/{{ ansible_user_id }}/workspace
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0755'
      become: no

    - name: Display installation summary
      debug:
        msg:
          - "Development environment setup complete!"
          - "Common packages installed: {{ common_packages | length }}"
          - "Programming tools installed: {{ programming_tools | length }}"
          - "Workspace created at: /home/{{ ansible_user_id }}/workspace"
